/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedReadRouteImport } from './routes/_authenticated/read'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCelebrationRankRouteImport } from './routes/_authenticated/celebration.rank'
import { Route as AuthenticatedCelebrationBookRouteImport } from './routes/_authenticated/celebration.book'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/_authenticated/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/_authenticated/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReadRoute = AuthenticatedReadRouteImport.update({
  id: '/_authenticated/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/_authenticated/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/_authenticated/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/_authenticated/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/_authenticated/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/_authenticated/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCelebrationRankRoute =
  AuthenticatedCelebrationRankRouteImport.update({
    id: '/_authenticated/celebration/rank',
    path: '/celebration/rank',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCelebrationBookRoute =
  AuthenticatedCelebrationBookRouteImport.update({
    id: '/_authenticated/celebration/book',
    path: '/celebration/book',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/read': typeof AuthenticatedReadRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/': typeof AuthenticatedIndexRoute
  '/celebration/book': typeof AuthenticatedCelebrationBookRoute
  '/celebration/rank': typeof AuthenticatedCelebrationRankRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/read': typeof AuthenticatedReadRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/': typeof AuthenticatedIndexRoute
  '/celebration/book': typeof AuthenticatedCelebrationBookRoute
  '/celebration/rank': typeof AuthenticatedCelebrationRankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/read': typeof AuthenticatedReadRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/celebration/book': typeof AuthenticatedCelebrationBookRoute
  '/_authenticated/celebration/rank': typeof AuthenticatedCelebrationRankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analytics'
    | '/friends'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/read'
    | '/resources'
    | '/summary'
    | '/'
    | '/celebration/book'
    | '/celebration/rank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/friends'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/read'
    | '/resources'
    | '/summary'
    | '/'
    | '/celebration/book'
    | '/celebration/rank'
  id:
    | '__root__'
    | '/_authenticated/analytics'
    | '/_authenticated/friends'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/quiz'
    | '/_authenticated/read'
    | '/_authenticated/resources'
    | '/_authenticated/summary'
    | '/_authenticated/'
    | '/_authenticated/celebration/book'
    | '/_authenticated/celebration/rank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedReadRoute: typeof AuthenticatedReadRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCelebrationBookRoute: typeof AuthenticatedCelebrationBookRoute
  AuthenticatedCelebrationRankRoute: typeof AuthenticatedCelebrationRankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/read': {
      id: '/_authenticated/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof AuthenticatedReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/celebration/rank': {
      id: '/_authenticated/celebration/rank'
      path: '/celebration/rank'
      fullPath: '/celebration/rank'
      preLoaderRoute: typeof AuthenticatedCelebrationRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/celebration/book': {
      id: '/_authenticated/celebration/book'
      path: '/celebration/book'
      fullPath: '/celebration/book'
      preLoaderRoute: typeof AuthenticatedCelebrationBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedReadRoute: AuthenticatedReadRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCelebrationBookRoute: AuthenticatedCelebrationBookRoute,
  AuthenticatedCelebrationRankRoute: AuthenticatedCelebrationRankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
