/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ReadRouteImport } from './routes/read'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelebrationRankRouteImport } from './routes/celebration.rank'
import { Route as CelebrationBookRouteImport } from './routes/celebration.book'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationRankRoute = CelebrationRankRouteImport.update({
  id: '/celebration/rank',
  path: '/celebration/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrationBookRoute = CelebrationBookRouteImport.update({
  id: '/celebration/book',
  path: '/celebration/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/read': typeof ReadRoute
  '/summary': typeof SummaryRoute
  '/celebration/book': typeof CelebrationBookRoute
  '/celebration/rank': typeof CelebrationRankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/read': typeof ReadRoute
  '/summary': typeof SummaryRoute
  '/celebration/book': typeof CelebrationBookRoute
  '/celebration/rank': typeof CelebrationRankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/read': typeof ReadRoute
  '/summary': typeof SummaryRoute
  '/celebration/book': typeof CelebrationBookRoute
  '/celebration/rank': typeof CelebrationRankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/quiz'
    | '/read'
    | '/summary'
    | '/celebration/book'
    | '/celebration/rank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/quiz'
    | '/read'
    | '/summary'
    | '/celebration/book'
    | '/celebration/rank'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/quiz'
    | '/read'
    | '/summary'
    | '/celebration/book'
    | '/celebration/rank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  QuizRoute: typeof QuizRoute
  ReadRoute: typeof ReadRoute
  SummaryRoute: typeof SummaryRoute
  CelebrationBookRoute: typeof CelebrationBookRoute
  CelebrationRankRoute: typeof CelebrationRankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebration/rank': {
      id: '/celebration/rank'
      path: '/celebration/rank'
      fullPath: '/celebration/rank'
      preLoaderRoute: typeof CelebrationRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebration/book': {
      id: '/celebration/book'
      path: '/celebration/book'
      fullPath: '/celebration/book'
      preLoaderRoute: typeof CelebrationBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  QuizRoute: QuizRoute,
  ReadRoute: ReadRoute,
  SummaryRoute: SummaryRoute,
  CelebrationBookRoute: CelebrationBookRoute,
  CelebrationRankRoute: CelebrationRankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
